import javax.swing.*;
import java.sql.*;

/**
 *
 * @author Rakshitha P
 */
public class AdminUpdater extends javax.swing.JFrame {
    private UpdateUsers parent;
    private static final String DB_URL = "jdbc:mysql://localhost:3306/bugtrackingsystem";
    private static final String DB_USER = "root";
    private static final String DB_PASSWORD = "root";

    /**
     * Creates new form AdminUpdater
     */
    public AdminUpdater(UpdateUsers parent) {
        this.parent = parent;
        setTitle("Admin Updater");
        initComponents();
        setLocationRelativeTo(null);
        loadAdmins();

        // Back button
        jButton1.addActionListener(evt -> {
            parent.setVisible(true);
            this.dispose();
        });

        // Update button
        jButton2.addActionListener(evt -> updateAdmin());
    }

    /**
     * Loads all Admins from the database into the combo box
     */
    private void loadAdmins() {
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
             PreparedStatement ps = conn.prepareStatement("SELECT name FROM users WHERE role = 'Admin'")) {

            ResultSet rs = ps.executeQuery();
            jComboBox1.removeAllItems();
            jComboBox1.addItem("Select");

            while (rs.next()) {
                jComboBox1.addItem(rs.getString("name"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error loading admins: " + ex.getMessage());
        }
    }

    /**
     * Updates selected Admin information
     */
    private void updateAdmin() {
        String adminName = (String) jComboBox1.getSelectedItem();
        String field = (String) jComboBox2.getSelectedItem();
        String newValue = jTextField1.getText().trim();

        if (adminName.equals("Select") || field.equals("Select") || newValue.isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠ Please fill all fields correctly!");
            return;
        }

        String column;
        switch (field) {
            case "Name": column = "name"; break;
            case "E-mail": column = "email"; break;
            case "Password": column = "password"; break;
            default: JOptionPane.showMessageDialog(this, "Invalid field selected."); return;
        }

        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
             PreparedStatement ps = conn.prepareStatement(
                     "UPDATE users SET " + column + " = ? WHERE name = ? AND role = 'Admin'")) {

            ps.setString(1, newValue);
            ps.setString(2, adminName);

            int rows = ps.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "✅ Admin updated successfully!");
                jTextField1.setText("");
                loadAdmins(); // Refresh list
            } else {
                JOptionPane.showMessageDialog(this, "Admin not found or not updated!");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error updating admin: " + ex.getMessage());
        }
    }

    // --------------------------------------------------------------
    //  GUI CODE GENERATED BY NETBEANS (edit only labels/text)
    // --------------------------------------------------------------
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Choose Admin Name:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Choose Field to Update:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Name", "E-mail", "Password" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Enter New Value:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1.setText("Back");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton2.setText("Update");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, 0, 220, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    // Variables declaration
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
}
