import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rakshitha P
 */
public class PerformanceResultWindow extends javax.swing.JFrame {

    /**
     * Creates new form PerformanceResultWindow
     */
    public PerformanceResultWindow(String title, String[] columns, Object[][] data) {
        setTitle("Performance Result");
        setSize(600, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        JTable table = new JTable(new DefaultTableModel(data, columns));
        JScrollPane scrollPane = new JScrollPane(table);

        JLabel summaryLabel = new JLabel(title, SwingConstants.CENTER);
        summaryLabel.setFont(new Font("Tahoma", Font.BOLD, 16));

        getContentPane().add(summaryLabel, BorderLayout.NORTH);
        getContentPane().add(scrollPane, BorderLayout.CENTER);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       String[] columns = {"Name", "Bugs Reported", "Bugs Fixed", "Performance"};
        Object[][] data = {
            {"DevA", 10, 8, "80%"},
            {"DevB", 12, 10, "83%"},
            {"DevC", 15, 14, "93%"}
        };

        SwingUtilities.invokeLater(() ->
            new PerformanceResultWindow("Developer Performance", columns, data).setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
